spring:
  application:
    name: rentiq-api

  datasource:
    url: "jdbc:postgresql://${RENDER_DB_HOST}:${RENDER_DB_PORT:5432}/${RENDER_DB_NAME}?sslmode=require"
    username: "${RENDER_DB_USERNAME}"
    password: "${RENDER_DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: "${CLIENT_ID:rentiq-client}"
            client-secret: "${CLIENT_SECRET}"
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            issuer-uri: "${ISSUER_URI:http://localhost:8080/realms/rentiq-app}"

      resourceserver:
        jwt:
          issuer-uri: "${ISSUER_URI:http://localhost:8080/realms/rentiq-app}"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8282

keycloak:
  server-url: "${SERVER_URL:http://127.0.0.1:8080}"
  client-id: "${CLIENT_ID:rentiq-client}"
  client-secret: "${CLIENT_SECRET}"
  realm: "${REALM:master}"
  target-realm: "${TARGET_REALM:rentiq-app}"
  redirect-uri: "http://localhost:8081/auth/callback"

cloudinary:
  cloud-name: "${CLOUDINARY_CLOUD_NAME}"
  api-key: "${CLOUDINARY_API_KEY}"
  api-secret: "${CLOUDINARY_API_SECRET}"