spring:
  application:
    name: rentiq-api

  security:
    oauth2:

      # Resource Server JWT
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

      # OAuth2 Client for Keycloak login
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}

  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5434/rentiq_db}"
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB


server:
  port: "${PORT:8282}"

  servlet:
    session:
      cookie:
        secure: false


keycloak:
  server-url: ${SERVER_URL}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  realm: ${REALM}
  target-realm: ${TARGET_REALM}


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


app:
  frontend-url: "${FRONTEND_URL:http://localhost:3000}"
  cors:
    allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:3000}"


logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.hibernate.SQL: INFO