package co.istad.rentiq_api.features.adminAudit.enums;

/** Exact action values accepted by the legacy PostgreSQL CHECK constraint. */
public enum AdminAuditPersistedAction {
    USER_SUSPENDED,
    USER_BANNED,
    USER_REINSTATED,
    VENDOR_APPLICATION_APPROVED,
    VENDOR_APPLICATION_REJECTED,
    VENDOR_SUSPENDED,
    VENDOR_BANNED,
    VENDOR_REINSTATED,
    KYC_APPROVED,
    KYC_REJECTED,
    ITEM_APPROVED,
    ITEM_REJECTED,
    ITEM_REMOVED,
    ITEM_FEATURED,
    ITEM_UNFEATURED,
    BOOKING_STATUS_CHANGED,
    DISPUTE_RESOLVED,
    REPORT_STATUS_CHANGED,
    MODERATION_ACTION_CREATED,
    REVIEW_HIDDEN,
    REVIEW_RESTORED,
    WALLET_CREDITED,
    WALLET_DEBITED,
    TOPUP_CONFIRMED,
    COMMISSION_RATE_UPDATED
}
